swagger: "2.0"
info:
  description: "El presente documento muestra los datos requeridos y la especificacion, para el envio de eventos por servicios web - RESTful, a la plataforma de Motum Cloud."
  version: "1.0.0"
  title: "Motum Cloud Services"
  termsOfService: "https://tecnomotum.com.mx"
  contact:
    email: "victormlzone@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "omega-metric-179905.appspot.com"
basePath: "/WSEndpoint"
tags:
- name: "Metodos de posiciones y eventos"
  description: "Procesa las posiciones y los eventos de Motum"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /events:
    post:
      tags:
      - "events"
      summary: "Registra uno o varios eventos"
      operationId: "events"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Event object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Event"
      # Removing API Key restriction for a method
      security: []
#      - api_key: []
      responses:
        202:
          description: "Accepted data"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "One/all data have errors"
          schema:
            $ref: "#/definitions/ApiResponse"
        403:
          description: "User is not allowed to use this resource"
          schema:
            $ref: "#/definitions/ApiResponse"
            
  /positions:
    post:
      tags:
      - "positions"
      summary: "Registra una o varias posiciones"
      operationId: "positions"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Position object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Position"
# Removing API Key restriction for a method
      security: []
#      - api_key: []
      responses:
        202:
          description: "Accepted data"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "One/all data have errors"
          schema:
            $ref: "#/definitions/ApiResponse"
        403:
          description: "User is not allowed to use this resource"
          schema:
            $ref: "#/definitions/ApiResponse"
         
definitions:
  
  Event:
    type: "object"
    
  Position:
    type: "object"
    
  
  ApiResponse:
    type: "object"
  
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  
externalDocs:
  description: "Find out more about TecnoMotum"
  url: "https://tecnomotum.com.mx/"